#!/bin/bash
clear
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'
echo Start
DIR_NAME=$(dirname "$0" | tr ' ' '\ ')
chmod 400 "$DIR_NAME/.key/id_rsa"
export GIT_SSH_COMMAND="ssh -i $DIR_NAME/.key/id_rsa -o IdentitiesOnly=yes"
cd "$DIR_NAME"
git config user.name "GitHub Actions" --local
git config user.email "41898282+github-actions[bot]@users.noreply.github.com" --local
git remote set-url origin git@github.com:LibertyCarz/icons.git
git checkout gh-pages
rm -rf .temp/carz-customer .temp/carz-merchant
cp -R carz-customer carz-merchant .temp
git reset --hard gh-pages
git pull origin gh-pages
rm -rf carz-customer carz-merchant
cp -R .temp/carz-customer .temp/carz-merchant ./
rm -rf carz-customer/index.html carz-merchant/index.html
cp carz-customer/demo.html carz-customer/index.html
cp carz-merchant/demo.html carz-merchant/index.html
git add -A
git commit -m 'feat: update icon'
git push origin gh-pages
printf "${GREEN}Finish${NC}\n"
