#!/bin/bash
clear
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'
echo Start
DIR_NAME=$(dirname "$0" | tr ' ' '\ ')
chmod 400 "$DIR_NAME/.key/id_rsa"
export GIT_SSH_COMMAND="ssh -i $DIR_NAME/.key/id_rsa -o IdentitiesOnly=yes"
cd "$DIR_NAME"
git config user.name "GitHub Actions" --local
git config user.email "41898282+github-actions[bot]@users.noreply.github.com" --local
git remote set-url origin git@github.com:LibertyCarz/icons.git
mkdir .temp
rm -rf .temp/SVG
mv SVG .temp
git reset --hard origin/main
git prune
git pull origin main
rm -rf SVG
mv .temp/SVG ./
rm -rf .temp
git add -A
git commit -m ':white_check_mark: update icon'
git push origin main
printf "${GREEN}Finish${NC}\n"