#!/bin/bash
clear
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'
echo Start
DIR_NAME=$(dirname "$0" | tr ' ' '\ ')
chmod 400 "$DIR_NAME/.key/id_rsa"
export GIT_SSH_COMMAND="ssh -i $DIR_NAME/.key/id_rsa -o IdentitiesOnly=yes"
cd "$DIR_NAME"
git config user.name "GitHub Actions" --local
git config user.email "41898282+github-actions[bot]@users.noreply.github.com" --local
git remote set-url origin git@github.com:LibertyCarz/icons.git
git checkout gh-pages
rm -rf .temp/customer .temp/merchant
cp -R customer merchant .temp
git reset --hard gh-pages
git pull origin gh-pages
rm -rf customer merchant
cp -R .temp/customer .temp/merchant ./
rm -rf customer/index.html merchant/index.html
cp customer/demo.html customer/index.html
cp merchant/demo.html merchant/index.html
git add -A
git commit -m 'feat: update icon'
git push origin gh-pages
printf "${GREEN}Finish${NC}\n"
