---
name: Automatic issue responses
on:
  push:
    branches:
      - feat/auto-generate-icon
jobs:
  build:
    name: Build iconmoon
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: npm install
        run: npm install
