---
name: carz merchant
on:
  push:
    branches:
      - carz-merchant
jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-22.04
    steps:
      - name: Hello World
        run: echo hello world
