---
name: Automatic issue responses
on:
  push:
    branches:
      - carz-merchant
jobs:
  build:
    name: Build iconmoon
    runs-on: [macos-latest]
    steps:
      - name: Check out Git repository (Core branch)
        uses: actions/checkout@v4
        with:
          ref: core
          path: core

      - name: Check out Git repository (carz-merchant branch)
        uses: actions/checkout@v4
        with:
          ref: carz-merchant
          path: app

      - name: Check out Git repository (gh-pages branch)
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Run npm install
        run: cd core &&  npm install

      - name: Run npm start
        run: cd core && npm start

      - name: Move carz-merchant file
        run: rm -rf gh-pages/carz-merchant && mv core/output gh-pages/carz-merchant

      - name: Move carz-merchant file
        run: rm -rf gh-pages/carz-merchant && mv core/output gh-pages/carz-merchant

      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd gh-pages
          git config user.name "GitHub Actions" --local
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com" --local
          git remote set-url origin git@github.com:LibertyCarz/icons.git
          git status
          git add -A
          git commit -m ':white_check_mark: update carz merchant icon'
          git push origin gh-pages
