---
name: Automatic issue responses
on:
  push:
    branches:
      - carz-customer
jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-22.04
    steps:
      - name: Hello World
        run: echo hello world
