---
name: Automatic issue responses
on:
  push:
    branches:
      - feat/auto-generate-icon
jobs:
  build:
    name: Build iconmoon
    runs-on: [macos-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        path: core
        ref: core

      - name: Check out Git repository
        uses: actions/checkout@v3
        ref: carz-merchant
        path: app

      - name: npm install
        run: cd core &&  npm install

      - name: npm start
        run: cd core && npm start

      - name: npm start
        run: cd core/output && ls
