---
name: Deployment File
on:
  push:
    branches:
      - carz-customer
      - carz-merchant
jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-22.04
    steps:
      - name: Hello World
        run: echo hello world
