name: Notification

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed

env:
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Send success telegram message
        uses: tuanngocptn/discord-action@main
        with:
          message: "🏁 - Finish deployment Icons set: https://icons.libertycarz.com/"